# Generated by Django 6.1.1 on 2026-10-05 08:12

import catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('client_ipi', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('iprs', 'IPRS report'), ('master', 'MRM master (LNV)'), ('prs', 'PRS works export')], max_length=20)),
                ('file', models.FileField(upload_to=catalogue.models.upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='catalogue.run')),
            ],
        ),
        migrations.CreateModel(
            name='LinkDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_no', models.CharField(max_length=40)),
                ('master_row', models.IntegerField(blank=True, null=True)),
                ('rejected_rows', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='catalogue.run')),
            ],
            options={
                'unique_together': {('run', 'internal_no')},
            },
        ),
    ]
