# Generated by Django 6.1.1 on 2026-10-05 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ipi', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='run',
            name='summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='run',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='catalogue.client'),
        ),
        migrations.CreateModel(
            name='ActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_key', models.CharField(max_length=60)),
                ('target', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('todo', 'To do'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('done', 'Done'), ('ignored', 'Not needed')], default='todo', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='catalogue.run')),
            ],
            options={
                'unique_together': {('run', 'song_key', 'target')},
            },
        ),
    ]
