# Generated by Django 6.1.1 on 2026-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_client_run_summary_run_client_actionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='owner',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='run',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
