# Generated by Django 6.1.1 on 2026-10-06 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_client_due_date_client_owner_run_report_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkdecision',
            name='master_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('register', 'Register'), ('add_client_credit', 'Add client credit'), ('correct_credits', 'Correct writers / shares'), ('merge_duplicates', 'Merge duplicate registrations'), ('fix_master', 'Fix our master')], max_length=30)),
                ('state', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('submitted', 'Submitted'), ('verified', 'Verified in report'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('detail', models.JSONField(blank=True, default=list)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalogue.client')),
                ('closed_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
                ('opened_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
            ],
        ),
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalogue.task')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrm_id', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('identifiers', models.JSONField(blank=True, default=dict)),
                ('language', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('origin', models.CharField(default='master', max_length=10)),
                ('master_row', models.IntegerField(blank=True, null=True)),
                ('credits', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='catalogue.client')),
                ('first_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
                ('last_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('client', 'mrm_id')},
            },
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalogue.work'),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('codes', models.JSONField(blank=True, default=list)),
                ('found_by', models.CharField(blank=True, max_length=60)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='catalogue.work')),
            ],
            options={
                'unique_together': {('work', 'society')},
            },
        ),
        migrations.CreateModel(
            name='WorkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=30)),
                ('text', models.TextField()),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalogue.run')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='catalogue.work')),
            ],
            options={
                'ordering': ['at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='ActionItem',
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('work', 'society', 'type')},
        ),
    ]
