# Generated by Django 6.1.1 on 2026-10-06 07:13

import catalogue.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_linkdecision_master_title_task_taskevent_work_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='home_society',
            field=models.CharField(default='IPRS', max_length=20),
        ),
        migrations.AddField(
            model_name='run',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='confirmed_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='run',
            name='society',
            field=models.CharField(default='IPRS', max_length=20),
        ),
        migrations.CreateModel(
            name='MasterFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=300, upload_to=catalogue.models.master_path)),
                ('original_name', models.CharField(max_length=255)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='catalogue.client')),
            ],
        ),
        migrations.CreateModel(
            name='ClientSociety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('society', models.CharField(max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='societies', to='catalogue.client')),
            ],
            options={
                'ordering': ['added_at', 'id'],
                'unique_together': {('client', 'society')},
            },
        ),
    ]
