# Generated by Django 6.1.1 on 2026-10-07 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_move_master_to_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_row', models.IntegerField()),
                ('field', models.CharField(max_length=20)),
                ('internal_no', models.CharField(max_length=40)),
                ('choice', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_edits', to='catalogue.client')),
            ],
            options={
                'unique_together': {('client', 'master_row', 'field')},
            },
        ),
    ]
