# Generated by Django 6.1.1 on 2026-10-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_master_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('flag', models.CharField(default='not_our_work', max_length=30)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_flags', to='catalogue.client')),
            ],
            options={
                'unique_together': {('client', 'key', 'flag')},
            },
        ),
    ]
